[build]
  functions = ".netlify/functions"

[functions]
  external_node_modules = ["@google/generative-ai"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200